### ISSUE TITLE
I'm quite sure python 3.8 is needed, not 3.3

### ISSUE THREAD

**Issue by majek** [amluto/virtme#55]
On python 3.5 I get this error
```
marek@mrnew:/build/virtme$  python3 ./virtme-run   
Traceback (most recent call last):
  File "./virtme-run", line 17, in <module>
    from virtme.commands import run
  File "/cfsetup_build/virtme/virtme/commands/run.py", line 37
    g: Any
     ^
SyntaxError: invalid syntax
```

**Comment by KamasuOri** [comment]
you must run with python 3.8

**Comment by amluto** [comment]
Is there any reasonably well supported way to strip out the typing annotations for the benefit of old python versions?

**Comment by majek** [comment]
Readme says:

```
Your host system will need to satisfy some prerequisites:

    You need Python 3.3 or higher.
```

**Comment by marcosps** [comment]
Well, I've being using virtme using openSUSE Leap 15.3 default python: 3.6.15, and it works. Maybe we should require python 3.6 or higher?

@KamasuOri can you say which problems you have when running version 3.6 for example? Per docs.python.org, typing support appeard on python 3.5.9.

**Comment by alexandrevicenzi** [comment]
Python 3.6 and lower already reached EOL, Leap 15.3 will reach EOL soon as well.

**Comment by marcosps** [comment]
@amluto what do you think? Maybe better to advise virtme with python 3.8?

**Comment by sskras** [comment]
Or maybe use Python 3.7 at the very least:
![image](https://user-images.githubusercontent.com/7887758/189978388-bb694077-b4b2-4a8f-98d4-56b14d030d70.png)
https://endoflife.date/python
