### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './.virtme_mods/lib/modules/0.0.0/modules.dep'

### ISSUE THREAD

**Issue by cng3s** [amluto/virtme#87]
# virtme-configkernel --arch=x86_64 --defconfig
# make ARCH=x86 CROSS_COMPILE=x86_64-linux-gnu- -j12
# virtme-run --kdir .
Traceback (most recent call last):
  File "/usr/local/bin/virtme-run", line 33, in <module>
    sys.exit(load_entry_point('virtme==0.1.1', 'console_scripts', 'virtme-run')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/virtme-0.1.1-py3.11.egg/virtme/commands/run.py", line 587, in main
    return do_it()
           ^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/virtme-0.1.1-py3.11.egg/virtme/commands/run.py", line 273, in do_it
    kernel = find_kernel_and_mods(arch, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/virtme-0.1.1-py3.11.egg/virtme/commands/run.py", line 201, in find_kernel_and_mods
    is_file_more_recent(mod_file, virtme_mod_file):
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/virtme-0.1.1-py3.11.egg/virtme/commands/run.py", line 135, in is_file_more_recent
    return os.stat(a).st_mtime > os.stat(b).st_mtime
                                 ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './.virtme_mods/lib/modules/0.0.0/modules.dep'

**Comment by marcosps** [comment]
@cng3s unfortunately the maintainer of virtme is not looking at issues anymore. Would you please check if the same bug exists on https://github.com/arighi/virtme-ng ? virtme-ng is an effort of maintain virtme and also create another tool on top of it.
